### PR TITLE
Naga server crash fix

### PR DESCRIPTION
**Pull request by naqaden**

### CODE REVIEW

**Comment by BobMowzie** [comment]
I'm almost certain that the crash was caused by the call to a field "dc" on the server even though that field was marked client-side only. This specific issue was addressed already in a commit, but I have yet to thoroughly test and release it.
I have not seen any reports of setRenderDistanceWeight causing crashes. Is this something you've seen before?

**Comment by naqaden** [comment]
Yes, I tried the indev build with the fix on the "dc" field since that crashed my server, only to crash again on the next line. It turns out setRenderDistanceWeight is also clientside code so I tucked it in with your fix.

**Comment by BobMowzie** [comment]
Thanks, I hadn't had a chance to test yet.

**Comment by BobMowzie** [comment]
If you have a chance, I suspect another crash is occurring from the geomancy "tunneling" ability. I'll test it myself soon enough, but in the meantime, please let me know if you encounter something there.

**Comment by naqaden** [comment]
I just tested multiplayer tunneling. The current release kicks me from the server, but I've had no issue with the indev build.

**Pull request merged**
